support release-notes

diff --git a/gud-add-location b/gud-add-location
--- a/gud-add-location
+++ b/gud-add-location
@@ -1,14 +1,28 @@
 #!/bin/sh
 
-HELPDIR=gnome-help
-POT=gnome-help.pot
-
 usage() {
   CMD=`basename $0`
   echo "Usage: $CMD [POFILE]"
   echo "  If POFILE is not specified, ja/ja.po will be used."
   echo "  Note: This command must be executed in the $HELPDIR directory."
 }
+
+MODULE=`git remote -v | sed -n -e 's!^.*git.gnome.org.*/\([[:alnum:]+-]\{1,\}\) (fetch)$!\1!p' | head -n 1`
+case "$MODULE" in
+  gnome-user-docs)
+    HELPDIR=gnome-help
+    POT=gnome-help.pot
+    ;;
+  release-notes)
+    HELPDIR=help
+    POT=release-notes.pot
+    ;;
+  *)
+    echo "Error: The module '${MODULE}' is unknown. It must be 'gnome-user-docs' or 'release-notes'."
+    exit 1
+    ;;
+esac
+
 
 OPT=`getopt h "$@"`
 if [ $? -ne 0 ]; then
diff --git a/gud-fmt-po b/gud-fmt-po
--- a/gud-fmt-po
+++ b/gud-fmt-po
@@ -6,6 +6,22 @@ usage() {
   echo "  Note: This command must be executed in the repository directory."
 }
 
+MODULE=`git remote -v | sed -n -e 's!^.*git.gnome.org.*/\([[:alnum:]+-]\{1,\}\) (fetch)$!\1!p' | head -n 1`
+case "$MODULE" in
+  gnome-user-docs)
+    HELPDIR=gnome-help
+    BRANCH=origin/master
+    ;;
+  release-notes)
+    HELPDIR=help
+    BRANCH=origin/gnome-3-6
+    ;;
+  *)
+    echo "Error: The module '${MODULE}' is unknown. It must be 'gnome-user-docs' or 'release-notes'."
+    exit 1
+    ;;
+esac
+
 OPT=`getopt h "$@"`
 if [ $? -ne 0 ]; then
   usage >&2
@@ -36,5 +52,5 @@ if [ ! -f "$PO" ]; then
   usage >&2
   exit 1
 fi
-git cat-file -p origin/master:gnome-help/ja/ja.po | sed -n -e '1,/^$/p'
+git cat-file -p "${BRANCH}:${HELPDIR}/ja/ja.po" | sed -n -e '1,/^$/p'
 msgmerge --no-location --no-wrap --previous -q "$PO" "$PO" | sed -e '1,/^$/d'
